name: Config Test 1
description: Description in Config.yml = Config test 1 - Single template, single version, single default. Category = Test. Happy path test.
version: 1.0
category: Test
maintainer: Tani Fiduccia
license: 9087 license
projectURL: https://www.amazon.com/