version: '2'
.catalog:
  name: "Load Balancer Test"
  version: "1.0.0"
  uuid: lb-service-0
  description: "LB Services"
  questions:
    - variable: "TEST_STRING"
      label: "String"
      required: false
      default: "hello"
      type: "string"
services:
  nginxcontainer:
    start_on_create: true
  wp1:
    scale: 1
    start_on_create: true
  mysql:
    scale: 1
    start_on_create: true
  ubuntusservice:
    start_on_create: true
  lbpointingtonginx:
    scale: 2
    start_on_create: true
    lb_config:
      certs: []
      port_rules:
      - path: ''
        priority: 1
        protocol: http
        service: nginxcontainer
        source_port: 90
        target_port: 80
      - priority: 2
        protocol: http
        service: wp1
        source_port: 70
        target_port: 80
      - priority: 3
        protocol: http
        service: ubuntusservice
        source_port: 80
        target_port: 80
    health_check:
      healthy_threshold: 2
      response_timeout: 2000
      port: 42
      unhealthy_threshold: 3
      interval: 2000
