.catalog:
  name: "Multiple services"
  version: "2.0.0"
  description: "Services"
  uuid: mulitple-services-0
lb1:
  scale: 2
  load_balancer_config:
    haproxy_config: {}
  health_check:
    port: 42
    interval: 2000
    unhealthy_threshold: 3
    strategy: recreate
    response_timeout: 2000
    healthy_threshold: 2

