.catalog:
  name: "Service Affinity rule check"
  version: "v1.6.7"
  description: Description in the rancher compose for Version 2
  minimum_rancher_version: v0.46.0
  maximum_rancher_version: v1.7.0
servicerelyingonlable:
  scale: 1
Service1withlabel:
  scale: 1
