name: Affinity Test 1achange
description: |
  This template sets up a service that has a label.  Then creates another service that relies on that label.  Both should end up on the same host. editing to bring it down again.

category: Test
maintainer: Tani Fiduccia
license: 9087 license
projectURL: http://www.google.com

