version: '2'
.catalog:
  name: "Add Load Balancer"
  version: "2.0"
  description: "Services"
services:
  loadbalancer:
    scale: 1
    start_on_create: true
    lb_config:
      certs: []
      port_rules:
      - hostname: 'testhostname.com'
        path: ''
        priority: 1
        protocol: http
        selector: loadbalancer.http=true
        source_port: 80
        target_port: 80
    health_check:
      healthy_threshold: 2
      response_timeout: 2000
      port: 42
      unhealthy_threshold: 3
      interval: 2000
      strategy: recreate