version: '2'
.catalog:
  name: "Selector Rule #2"
  version: "2.0"
  description: "Services"
services:
  collector:
    scale: 1
    start_on_create: true
    lb_config:
      port_rules:
      - hostname: test-1.example.com
        target_port: 90
    health_check:
      healthy_threshold: 2
      response_timeout: 2000
      port: 80
      unhealthy_threshold: 3
      initializing_timeout: 60000
      interval: 2000
      strategy: recreate
      reinitializing_timeout: 60000