.catalog:
  name: "Service Affinity rule check"
  version: 
  description: Description in the rancher compose.
  minimum_rancher_version: v0.46.0
servicerelyingonlable:
  scale: 1
Service1withlabel:
  scale: 1
