
SA1:
  image: rancher/dns-service
  links:
  - Service-ubuntu-global:Service-ubuntu-global

Service-ubuntu-global:
  log_driver: ''
  labels:
    io.rancher.scheduler.global: 'true'
    io.rancher.container.pull_image: always
  tty: true
  log_opt: {}
  image: ubuntu:14.04.3
  stdin_open: true
