name: Selector Rule Test 3
description: Testing changing hostname through a service's lb_config
version: 1.0
category: Test
maintainer: Tani Fiduccia
license: 9087 license
projectURL: https://www.amazon.com/